@startuml
title 物件探しシーケンス
actor user
participant 不動産サイト
actor 不動産会社
actor 大家
participant 物件

user -> 不動産サイト: 物件検索
loop 
    user -> 不動産会社: 内見申し込み
    activate 不動産会社
        不動産会社 -> 大家: 内見依頼
        activate 大家
            大家 -> 不動産会社: 鍵の受け渡し
        deactivate 大家
        user -> 不動産会社: 待ち合い
        不動産会社 -> 物件: 内見
    deactivate 不動産会社

    alt 物件が良かった
        不動産会社 -> 大家: 物件確保の連絡
        大家 -> 不動産会社: 空き家の解除申請
        不動産会社 -> 不動産サイト: 空き家ステータスの更新
        不動産会社 -> user: 物件の手続き
        user --> 不動産会社
        user -> 物件: 入居
    else 思っていたものと違った
        user -> 不動産会社: 物件の希望条件すり合わせ
        不動産会社 --> user
        不動産会社 -> 不動産サイト:新しい物件検索
        不動産会社 -> user: 内見したい物件を選ぶ
        user -> 不動産会社: 再度内見申し込み
    end
end
@enduml
